name: Create GitHub Issue

on:
  push:
    branches:
      - master

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: |
          python create_issue.py
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
